class InterpTooLong(BaseException): pass
class ExpectedStdin(BaseException): pass
class ExpectedStdout(BaseException): pass
class ExpectedStderr(BaseException): pass
class ExpectedReturn(BaseException): pass
class IncorrectStdout(BaseException): pass
class IncorrectStderr(BaseException): pass
class IncorrectReturn(BaseException): pass
class PassedAllTestSteps(BaseException): pass
class SegmentationFault(BaseException): pass
